### ISSUE TITLE
[Bug]: Jailing a person does nothing.

### ISSUE THREAD

**Issue by Garcello822** [wwosimulation/tracker#349] opened 2021-11-04 22:24 UTC
### What happened?

When jailer uses their command on somebody, nothing happens. They are not sent to jailed chat or locked out of their channel.

### What part of the bot are you seeing the problem on?

Game - Narrator

**Comment by Gorott** [comment] 2021-11-09 14:48
Duplicate of #340 so gonna close this

**Closed** 2022-01-10 09:07 UTC
Labels: Unverified, Bug, Role Interactions
