### ISSUE TITLE
Rose wheel check for enough roses fails

### ISSUE THREAD

**Issue by thewilloftheshadow** [wwosimulation/tracker#352] opened 2021-11-06 07:02 UTC
### What happened?

Gmo used the +rosewheel command without 30 roses and it charged him, causing him to have negative roses.

### What part of the bot are you seeing the problem on?

Economy

**Comment by thewilloftheshadow** [comment] 2021-11-06 07:03
I may have accidentally fixed this already, but needs testing

**Comment by Gmo666** [comment] 2021-11-06 07:04
Also pay 30 roses to get 5 roses scam

**Comment by Hackante** [comment] 2021-11-06 10:42
![image](https://user-images.githubusercontent.com/85803963/140606781-a7099584-5666-4829-b69b-ccc838ee8d76.png)
cannot reproduce

**Comment by thewilloftheshadow** [comment] 2021-11-06 16:16
https://discord.com/channels/465795320526274561/606123806490230784/906571695261896744

**Comment by inno14** [comment] 2021-12-15 11:13
Shouldn't this be closed as it is in "Complete" board ?

**Comment by Hackante** [comment] 2021-12-15 21:28
Yep. The bug was not produced by the code but for some reason it was the the one process that didn't work

**Closed by Hackante** 2021-12-15 21:28 UTC
Labels: Bug, Economy, High Priority
