### ISSUE TITLE
Bot doesn't give color role after buying from shop 

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#300] opened 2021-10-10 14:06 UTC
![Screenshot_20211010-193540_Discord](https://user-images.githubusercontent.com/83353462/136699102-b43ba0cb-d24d-4070-a5ab-e305cc84cc69.jpg)

**Comment by inno14** [comment] 2022-01-07 08:19
I think bot gives it

**Comment by Hackante** [comment] 2022-01-07 09:07
Duplicate of #342 will be fixed in the buy branch

**Closed** 2022-01-07 09:07 UTC
Labels: Bug, Economy, Invalid
