### ISSUE TITLE
/srole gamemode custom role: <roles> pins a rolelist as hidden

### ISSUE THREAD

**Issue by Accio-Aquamarine** [wwosimulation/tracker#329] opened 2021-10-20 18:51 UTC

**Comment by thewilloftheshadow** [comment] 2021-10-20 18:59
Duplicate of #297

**Closed as completed** 2021-10-20 19:00 UTC
Labels: Bug, Invalid

**Comment by Accio-Aquamarine** [comment] 2021-10-20 19:11
@thewilloftheshadow 297 is for hiding roles, as the roles doesn't remain hidden after death, whereas this issue is for getting pinned rolelist which is displayed as hidden even if not mentioned. (that is also added in `in addition to` in 297 but if I read right both issues are different and have different fixes
