### ISSUE TITLE
+bug 5 jailed 3 , but 3 watered someone and died and could still see #.jailed-chat

### ISSUE THREAD

**Issue by inno14** [wwosimulation/tracker#80] opened 2021-06-26 10:32 UTC
+bug 5 jailed 3 , but 3 watered someone and died and could still see #.jailed-chat 
2 images below 
![Screenshot_20210626-160051_Discord](https://user-images.githubusercontent.com/83353462/123510215-dfea1d80-d697-11eb-95b0-b2cdab0a986b.jpg)

![Screenshot_20210626-160039_Discord](https://user-images.githubusercontent.com/83353462/123510209-dc569680-d697-11eb-8f5f-ca3d22141824.jpg)

**Comment by thewilloftheshadow** [comment] 2021-06-26 14:22
Duplicate of #26

**Closed by thewilloftheshadow** 2021-06-26 14:22 UTC
